// lib/brochuresData.js
// Centralized metadata and configuration for 13 Dreams Study Abroad E-Magazines & Brochures

export const BROCHURES = [
  {
    id: 'australia',
    slug: 'australia',
    country: 'Australia',
    flag: '🇦🇺',
    code: 'AU',
    title: 'Australia Study Visa Comprehensive Guide 2025–2026',
    subtitle: 'Group of Eight (Go8), Subclass 500, GST & Post-Study Work Visa Handbook',
    description:
      'The authoritative handbook covering student visa Subclass 500, genuine student criteria, university admission requirements, post-study work rights up to 4-5 years, and PR pathways.',
    totalPages: 32,
    pdfUrl: 'https://res.cloudinary.com/eikgki2a/raw/upload/v1790160899/13dreams/brochures/pdfs/australia-study-visa-brochure.pdf',
    coverImage: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790160801/13dreams/brochures/covers/australia-cover.jpg',
    pagesDir: 'https://res.cloudinary.com/eikgki2a/image/upload/w_800,c_limit,f_auto,q_auto:good/13dreams/brochures/pages/australia',
    colorTheme: {
      primary: '#0D9488', // Teal/Ocean
      badge: 'bg-teal-50 text-teal-700 border-teal-200',
      gradient: 'from-teal-600 to-emerald-700',
      glow: 'shadow-teal-500/20',
    },
    specs: {
      intakes: 'Feb / Mar & Jul / Aug',
      workRights: '48 hrs / fortnight (Full-time in breaks)',
      pswDuration: '2 to 4+ Years (Extended in Regional)',
      ieltsScore: '6.0 UG / 6.5 PG (PTE 58+)',
      successRate: '99%',
      avgTuition: 'AUD $25,000 – $42,000 / year',
    },
    keyTopics: [
      'Student Visa Subclass 500 Documentation',
      'Genuine Student Test (GST) Strategy & SOP Preparation',
      'Group of Eight (Go8) & Top Australian Universities',
      'Part-Time Jobs & Minimum Hourly Wages (AUD $24.10+)',
      'Subclass 485 Temporary Graduate Visa Rules',
      'PR Pathway Points Calculator & Skilled Migration (189/190)',
    ],
  },
  {
    id: 'canada',
    slug: 'canada',
    country: 'Canada',
    flag: '🇨🇦',
    code: 'CA',
    title: 'Canada Study Visa & Immigration Blueprint 2025–2026',
    subtitle: 'SDS Process, DLI Institutions, PGWP Work Permits & PR Pathways',
    description:
      'Comprehensive master guide for studying in Canada. Covers SDS documentation, GIC accounts, provincial attestation letters (PAL), PGWP eligibility, and Express Entry PR options.',
    totalPages: 32,
    pdfUrl: 'https://res.cloudinary.com/eikgki2a/raw/upload/v1790160907/13dreams/brochures/pdfs/canada-study-visa-brochure.pdf',
    coverImage: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790160900/13dreams/brochures/covers/canada-cover.jpg',
    pagesDir: 'https://res.cloudinary.com/eikgki2a/image/upload/w_800,c_limit,f_auto,q_auto:good/13dreams/brochures/pages/canada',
    colorTheme: {
      primary: '#DC2626', // Red
      badge: 'bg-red-50 text-red-700 border-red-200',
      gradient: 'from-red-600 to-rose-700',
      glow: 'shadow-red-500/20',
    },
    specs: {
      intakes: 'Fall (Sep), Winter (Jan), Summer (May)',
      workRights: '24 hrs / week off-campus during terms',
      pswDuration: 'Up to 3-Year Open Work Permit (PGWP)',
      ieltsScore: '6.0 each module (PTE 60+)',
      successRate: '98.8%',
      avgTuition: 'CAD $16,000 – $32,000 / year',
    },
    keyTopics: [
      'SDS Student Direct Stream Checklist',
      'Guaranteed Investment Certificate (GIC - CAD $20,635)',
      'Provincial Attestation Letter (PAL) Step-by-Step',
      'Post-Graduation Work Permit (PGWP) New Regulations',
      'Spousal Open Work Permit Eligibility',
      'Canadian Experience Class & Provincial Nominee Programs (PNP)',
    ],
  },
  {
    id: 'germany',
    slug: 'germany',
    country: 'Germany',
    flag: '🇩🇪',
    code: 'DE',
    title: 'Germany Public Universities & Free Education Guide 2025–2026',
    subtitle: 'Tuition-Free Universities, APS Certificate & 18-Month Job Search Visa',
    description:
      'Official guide explaining how to secure admissions in world-class German public universities with zero tuition fees, APS certificate procedures, and EU Blue Card PR.',
    totalPages: 32,
    pdfUrl: 'https://res.cloudinary.com/eikgki2a/raw/upload/v1790160913/13dreams/brochures/pdfs/germany-study-visa-brochure.pdf',
    coverImage: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790160909/13dreams/brochures/covers/germany-cover.jpg',
    pagesDir: 'https://res.cloudinary.com/eikgki2a/image/upload/w_800,c_limit,f_auto,q_auto:good/13dreams/brochures/pages/germany',
    colorTheme: {
      primary: '#D97706', // Gold / Amber
      badge: 'bg-amber-50 text-amber-700 border-amber-200',
      gradient: 'from-amber-600 to-yellow-700',
      glow: 'shadow-amber-500/20',
    },
    specs: {
      intakes: 'Winter (Oct) & Summer (Apr)',
      workRights: '140 full days or 280 half days per year',
      pswDuration: '18-Month Job Seeking Visa (Aufenthaltserlaubnis)',
      ieltsScore: '6.5 overall (English-taught degrees)',
      successRate: '99.2%',
      avgTuition: '€0 (Free Public) – Semester fee €250–€350',
    },
    keyTopics: [
      'Top Tuition-Free German Public Universities (TU9 & Elite)',
      'Mandatory APS Certificate Verification for Indian Students',
      'Blocked Bank Account Setup (€11,904 requirement)',
      'English-Taught Master’s in AI, CS, Automotive & Data Science',
      'Post-Study 18-Month Job Search Visa (18-Monate Suchvisum)',
      'Fast-Track EU Blue Card & Permanent Residence (Niederlassungserlaubnis)',
    ],
  },
  {
    id: 'uk',
    slug: 'uk',
    country: 'United Kingdom',
    flag: '🇬🇧',
    code: 'GB',
    title: 'United Kingdom (UK) 1-Year Master’s & Career Handbook 2025–2026',
    subtitle: '1-Year Fast-Track Degrees, IELTS Waivers & 2-Year Graduate Route Visa',
    description:
      'In-depth handbook detailing how to save 1 full year on Master’s programs in the UK, secure full IELTS waivers, obtain CAS letters, and leverage 2-year post-study work permits.',
    totalPages: 32,
    pdfUrl: 'https://res.cloudinary.com/eikgki2a/raw/upload/v1790160927/13dreams/brochures/pdfs/uk-study-visa-brochure.pdf',
    coverImage: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790160922/13dreams/brochures/covers/uk-cover.jpg',
    pagesDir: 'https://res.cloudinary.com/eikgki2a/image/upload/w_800,c_limit,f_auto,q_auto:good/13dreams/brochures/pages/uk',
    colorTheme: {
      primary: '#1D4ED8', // Royal Blue
      badge: 'bg-blue-50 text-blue-700 border-blue-200',
      gradient: 'from-blue-600 to-indigo-800',
      glow: 'shadow-blue-500/20',
    },
    specs: {
      intakes: 'September/October & January/February',
      workRights: '20 hrs / week during terms (Full-time vacation)',
      pswDuration: '2-Year Graduate Route Visa (3 Years for PhD)',
      ieltsScore: '6.0 – 6.5 (Full IELTS Waiver with 70%+ in 12th)',
      successRate: '99.4%',
      avgTuition: '£13,000 – £26,000 / year',
    },
    keyTopics: [
      'Cost & Time Advantages of UK 1-Year Master’s Degrees',
      'IELTS Waiver Conditions (70%+ in CBSE/ICSE 12th Board English)',
      'Confirmation of Acceptance for Studies (CAS) Procedure',
      '2-Year Graduate Route Post-Study Work Visa Details',
      'Top Russell Group & Modern Industry-Linked Universities',
      'Skilled Worker Visa (Tier 2) Sponsorship Transition',
    ],
  },
  {
    id: 'usa',
    slug: 'usa',
    country: 'United States',
    flag: '🇺🇸',
    code: 'US',
    title: 'USA F-1 Student Visa & STEM OPT Handbook 2025–2026',
    subtitle: 'Form I-20, Embassy Interview Prep, 3-Year STEM OPT & Top Tech Careers',
    description:
      'Exclusive handbook on securing US university admissions, Form I-20 issuance, mastering the F-1 visa interview at US consulates, and unlocking 36 months of STEM OPT work authorization.',
    totalPages: 32,
    pdfUrl: 'https://res.cloudinary.com/eikgki2a/raw/upload/v1790160933/13dreams/brochures/pdfs/usa-study-visa-brochure.pdf',
    coverImage: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790160929/13dreams/brochures/covers/usa-cover.jpg',
    pagesDir: 'https://res.cloudinary.com/eikgki2a/image/upload/w_800,c_limit,f_auto,q_auto:good/13dreams/brochures/pages/usa',
    colorTheme: {
      primary: '#4338CA', // Indigo
      badge: 'bg-indigo-50 text-indigo-700 border-indigo-200',
      gradient: 'from-indigo-600 to-blue-800',
      glow: 'shadow-indigo-500/20',
    },
    specs: {
      intakes: 'Fall (August) & Spring (January)',
      workRights: '20 hrs / week on-campus (CPT / OPT available)',
      pswDuration: '36 Months Work Authorization (12m OPT + 24m STEM)',
      ieltsScore: '6.5 overall (Duolingo 115+ accepted)',
      successRate: '98.5%',
      avgTuition: 'USD $22,000 – $45,000 / year',
    },
    keyTopics: [
      'University Form I-20 Issuance & Financial Vetting',
      'SEVIS I-901 Fee & DS-160 Form Instructions',
      'US Visa Officer Mock Interview Questions & Strategies',
      '3-Year STEM OPT (12-month standard + 24-month STEM extension)',
      'Curricular Practical Training (CPT) Internships while studying',
      'H-1B Visa Transition & Silicon Valley Corporate Pathways',
    ],
  },
  {
    id: 'nz',
    slug: 'nz',
    country: 'New Zealand',
    flag: '🇳🇿',
    code: 'NZ',
    title: 'New Zealand Study & Post-Study Work Visa Handbook 2025–2026',
    subtitle: 'Level 7/8/9 Qualifications, Green List PR Occupations & Post-Study Visas',
    description:
      'Complete handbook exploring New Zealand’s high quality of life, Green List fast-track PR careers for STEM and Healthcare, up to 3 years open post-study work visas, and partner rights.',
    totalPages: 32,
    pdfUrl: 'https://res.cloudinary.com/eikgki2a/raw/upload/v1790160920/13dreams/brochures/pdfs/nz-study-visa-brochure.pdf',
    coverImage: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790160914/13dreams/brochures/covers/nz-cover.jpg',
    pagesDir: 'https://res.cloudinary.com/eikgki2a/image/upload/w_800,c_limit,f_auto,q_auto:good/13dreams/brochures/pages/nz',
    colorTheme: {
      primary: '#059669', // Emerald
      badge: 'bg-emerald-50 text-emerald-700 border-emerald-200',
      gradient: 'from-emerald-600 to-teal-800',
      glow: 'shadow-emerald-500/20',
    },
    specs: {
      intakes: 'February & July (Secondary: Nov)',
      workRights: '20 hrs / week during semesters (Full-time holidays)',
      pswDuration: 'Up to 3-Year Open Post-Study Work Visa',
      ieltsScore: '6.0 UG / 6.5 PG (PTE 58+)',
      successRate: '99%',
      avgTuition: 'NZD $24,000 – $38,000 / year',
    },
    keyTopics: [
      'Level 7 Graduate Diploma, Level 8 Postgrad, Level 9 Master’s',
      'New Zealand Green List Occupations with Direct-to-Residence PR',
      '3-Year Open Post-Study Work Visa Regulations',
      'Partner / Spousal Work Visa Eligibility',
      'Top 8 NZ Universities (All ranked in Top 2% globally)',
      'Pathway Student Visa and Financial Proof Requirements',
    ],
  },
];

export function getBrochureBySlug(slug) {
  return BROCHURES.find((b) => b.slug.toLowerCase() === slug.toLowerCase()) || null;
}
