// Curated Real Instagram Reels from 13 Dreams Consultants (@13dreamsconsultants)
export const instagramReelsData = [
  {
    id: 'DWBle0XiZmj',
    reelId: 'DWBle0XiZmj',
    studentName: 'Australia Study Visa Grant',
    title: 'Surprise Australia Study Visa Grant',
    countryOrScore: 'Australia Visa',
    category: 'visa',
    url: 'https://www.instagram.com/13dreamsconsultants/reel/DWBle0XiZmj/',
    date: 'Recent',
  },
  {
    id: 'Dbf5-aoxeNm',
    reelId: 'Dbf5-aoxeNm',
    studentName: 'Student Visa Celebration',
    title: 'Student Visa Approved Celebration',
    countryOrScore: 'Australia Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/Dbf5-aoxeNm/?stkn=bHFob3ZqaTkzdG5t',
    date: 'Recent',
  },
  {
    id: 'DXooiMQiCBG',
    reelId: 'DXooiMQiCBG',
    studentName: 'Overseas Study Dream',
    title: 'Overseas Study Dream Come True',
    countryOrScore: 'Canada Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DXooiMQiCBG/?stkn=aHhldm11MGdsOG5s',
    date: 'Recent',
  },
  {
    id: 'DWOiy3mEU6m',
    reelId: 'DWOiy3mEU6m',
    studentName: 'Australia Visa Handover',
    title: 'Australia Visa Handover Moment',
    countryOrScore: 'Australia Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DWOiy3mEU6m/?stkn=d3JpcHRkYm52emFx',
    date: 'Recent',
  },
  {
    id: 'DVi5h-PEcKp',
    reelId: 'DVi5h-PEcKp',
    studentName: 'Emotional Visa Success',
    title: 'Emotional Study Visa Success',
    countryOrScore: 'UK Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DVi5h-PEcKp/?stkn=MXF5cWt4Zjl0eTUzeQ==',
    date: 'Recent',
  },
  {
    id: 'DVQqyPSEWHN',
    reelId: 'DVQqyPSEWHN',
    studentName: 'USA Student Visa Approved',
    title: 'USA Student Visa Approved',
    countryOrScore: 'USA Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DVQqyPSEWHN/?stkn=ZHR6cTRmeTRlNzNi',
    date: 'Recent',
  },
  {
    id: 'DVIacDekT23',
    reelId: 'DVIacDekT23',
    studentName: 'Australia Study Visa Granted',
    title: 'Australia Study Visa Granted',
    countryOrScore: 'Australia Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DVIacDekT23/?stkn=NTYzaWlydTBxanR1',
    date: 'Recent',
  },
  {
    id: 'DU5gzuKkfXU',
    reelId: 'DU5gzuKkfXU',
    studentName: 'Fast-Track Student Visa',
    title: 'Fast-Track Student Visa Result',
    countryOrScore: 'Australia Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DU5gzuKkfXU/?stkn=MXN4Z2lucGhlazZycg==',
    date: 'Recent',
  },
  {
    id: 'DU0TXwfEXnp',
    reelId: 'DU0TXwfEXnp',
    studentName: 'Top University Admission',
    title: 'Top University Admission & Visa',
    countryOrScore: 'Canada Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DU0TXwfEXnp/?stkn=MWpqdWtwa20wbm5iNw==',
    date: 'Recent',
  },
  {
    id: 'DT2qW6dEdVf',
    reelId: 'DT2qW6dEdVf',
    studentName: 'Australia Higher Education',
    title: 'Australia Higher Education Grant',
    countryOrScore: 'Australia Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DT2qW6dEdVf/?stkn=MXJsbTRzZjZoY3I4ag==',
    date: 'Recent',
  },
  {
    id: 'DSaBYMakRj9',
    reelId: 'DSaBYMakRj9',
    studentName: 'Pure Happiness: Visa Grant',
    title: 'Pure Happiness: Student Visa Achieved',
    countryOrScore: 'UK Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DSaBYMakRj9/?stkn=am5zN3djMDMyeGhw',
    date: 'Recent',
  },
  {
    id: 'DSXWC37kTf-',
    reelId: 'DSXWC37kTf-',
    studentName: 'Canada Study Permit',
    title: 'Canada Study Permit Victory',
    countryOrScore: 'Canada Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DSXWC37kTf-/?stkn=dXdseHk1NjNjbWx1',
    date: 'Recent',
  },
  {
    id: 'DSSQwoekb9N',
    reelId: 'DSSQwoekb9N',
    studentName: 'UK Visa Approval Handover',
    title: 'UK Visa Approval Handover',
    countryOrScore: 'UK Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DSSQwoekb9N/?stkn=aHUycnA5MTVpZzBx',
    date: 'Recent',
  },
  {
    id: 'DSKtMI0Efjx',
    reelId: 'DSKtMI0Efjx',
    studentName: 'Visa Handover & Review',
    title: 'Visa Handover & Student Review',
    countryOrScore: 'Australia Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DSKtMI0Efjx/?stkn=MTY0N2QzZTg1OWozeg==',
    date: 'Recent',
  },
  {
    id: 'DRzOSjhkZTu',
    reelId: 'DRzOSjhkZTu',
    studentName: 'Australia Visa Celebration',
    title: 'Australia Visa Grant Celebration',
    countryOrScore: 'Australia Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DRzOSjhkZTu/?stkn=aWhvYjZzNXkwcGNr',
    date: 'Recent',
  },
  {
    id: 'DRwwjAFkQb4',
    reelId: 'DRwwjAFkQb4',
    studentName: 'New Zealand / Australia Journey',
    title: 'New Zealand / Australia Journey',
    countryOrScore: 'New Zealand Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DRwwjAFkQb4/?stkn=emlybGV2NnVydnBv',
    date: 'Recent',
  },
  {
    id: 'DRhSf7KEcFP',
    reelId: 'DRhSf7KEcFP',
    studentName: 'Student Visa Handover Experience',
    title: 'Student Visa Handover Experience',
    countryOrScore: 'Australia Visa',
    category: 'visa',
    url: 'https://www.instagram.com/reel/DRhSf7KEcFP/?stkn=MWRoeHY0aGtkYXlodQ==',
    date: 'Recent',
  },
];
