// ==========================================
// lib/pageData.js
// Centralised detail data for dynamic routes
// /service/[slug] and /study/[slug]
// ==========================================

export const servicePageData = {
  'comprehensive-counselling': {
    title: 'Comprehensive Counselling',
    subtitle: 'Personalized, unbiased academic and career mapping for international aspirants',
    metaTitle: 'Comprehensive Counselling | 13 Dreams Consultants',
    metaDesc: 'Expert course and career counseling for students planning to study abroad. One-on-one guidance based on academic profile, budget, and long-term career goals.',
    overview: 'We have professional counsellors who are experienced in effectively assisting students in their course and country of study selection. Navigating through thousands of international universities, varying admission prerequisites, and career outcomes can be overwhelming. Our comprehensive counseling evaluates your academic transcripts, aptitude, budget limitations, and post-graduation goals to craft a customized roadmap.',
    keyOfferings: [
      'One-on-one profiling assessment by senior study abroad advisors.',
      'Shortlisting of best-fit countries (Canada, UK, Australia, USA, Germany, NZ, Singapore, Malta).',
      'In-depth comparative analysis of tuition fees, cost of living, and part-time earning opportunities.',
      'Clear guidance on test requirements (IELTS, PTE, TOEFL, GRE, GMAT, Duolingo).',
      'Discussion of post-study work permits (PGWP, Subclass 485, Graduate Route) and PR opportunities.',
    ],
    processSteps: [
      'Initial Profile Review & Academic Assessment',
      'Course, Major, and Specialization Identification',
      'Shortlisting 3 to 5 Best-Fit Foreign Universities',
      'Budgeting, Fee Schedules, and Scholarship Probability Assessment',
      'Creation of a Month-by-Month Application Action Plan',
    ],
  },
  'application-processing': {
    title: 'Application Processing',
    subtitle: 'Expert-managed university admissions from shortlisting to offer letter',
    metaTitle: 'Application Processing | 13 Dreams Consultants',
    metaDesc: 'Streamlined university application processing, document submission, and offer letter procurement by 13 Dreams Consultants.',
    overview: 'Students often find the application process to be intimidating. Hence our team of skilled counsellors provides extensive hand-holding to help them submit polished and complete applications that maximize their offer letter success rate.',
    keyOfferings: [
      'Shortlisting universities matching academic merit, IELTS/PTE scores, and budget.',
      'Preparation of personal statements, letters of intent, and academic references.',
      'Online application filing on official university portals with document uploads.',
      'Following up directly with university admissions teams for faster processing.',
      'Procurement and verification of official offer letters and Confirmation of Acceptance (CAS/COE).',
    ],
    processSteps: [
      'University Shortlisting & Gap Analysis',
      'SOP & Reference Letter Drafting',
      'Online Application Submission',
      'Offer Letter & Unconditional Acceptance Procurement',
      'Admission Confirmation & Visa Stage Handover',
    ],
  },
  'advice-on-program-selection': {
    title: 'Advice on Selection of Programs',
    subtitle: 'Data-driven course matching based on academics, careers, and market demand',
    metaTitle: 'Advice on Program Selection | 13 Dreams Consultants',
    metaDesc: 'Professional guidance on selecting the right international program and specialization for your academic profile and career goals.',
    overview: 'We maintain frequent contact with the colleges we represent and remain up to speed on the various courses and programs of study they provide. Our advisors analyze global job markets to ensure your chosen program has strong employment outcomes.',
    keyOfferings: [
      'Comprehensive database of 150+ partner universities and their top programs.',
      'Matching your undergraduate stream to globally in-demand postgraduate specializations.',
      'Career outcomes research: average salaries, PR eligibility, and job placement rates.',
      'Guidance on bridging programs for career changers entering new disciplines abroad.',
    ],
    processSteps: [
      'Academic Transcript & Stream Review',
      'Career Goal Mapping & Market Analysis',
      'Program Universe Shortlisting',
      'Final Program Lock-in & Application Action Plan',
    ],
  },
  'assistance-with-scholarship-applications': {
    title: 'Scholarship Application Assistance',
    subtitle: 'Identifying and securing financial awards to ease your study abroad costs',
    metaTitle: 'Scholarship Application Assistance | 13 Dreams Consultants',
    metaDesc: 'Identify and secure university scholarships and bursaries that lighten the financial load of international higher studies.',
    overview: 'Identify and secure university scholarships and bursaries that lighten the financial load of international higher studies. We proactively research and advocate for merit and diversity scholarship awards at every partner institution.',
    keyOfferings: [
      'Comprehensive research across university merit scholarships, regional bursaries, and diversity grants.',
      'Early bird discount identification and application window tracking.',
      'Scholarship essay and statement of purpose coaching.',
      'Direct advocacy with university admissions panels for fee reduction consideration.',
    ],
    processSteps: [
      'Scholarship Eligibility Screening',
      'Application Window & Deadline Mapping',
      'Essay Formulation & Academic Recommendation Optimization',
      'Official Scholarship Application Lodgement & Award Confirmation',
    ],
  },
  'advice-on-student-visas': {
    title: 'Student Visa Guidance',
    subtitle: 'End-to-end visa documentation, financial proof, and mock interview preparation',
    metaTitle: 'Student Visa Guidance | 13 Dreams Consultants',
    metaDesc: 'End-to-end documentation scrutiny, financial sponsorship arrangement verification, and mock interview preparations for high visa success.',
    overview: 'End-to-end documentation scrutiny, financial sponsorship arrangement verification, and mock interview preparations for high visa success. Our visa team has maintained a 99% visa approval track record through meticulous compliance.',
    keyOfferings: [
      'Country-specific visa documentation checklists (Canada, UK, Australia, USA, Germany, NZ, Singapore, Malta).',
      'Financial sponsorship structure audits: bank balance, loan letters, GIC certificates, and blocked accounts.',
      'Statement of Purpose (SOP) drafting, review, and iteration cycles.',
      'Mock visa officer interviews and difficult question simulation practice.',
      'Post-submission tracking and prompt responses to embassy Requests for Further Information (RFI).',
    ],
    processSteps: [
      'Visa Documentation Checklist Review',
      'Financial Proof Assembly & Bank Statement Guidance',
      'SOP & Cover Letter Drafting',
      'Mock Interview Preparation & Final Document Verification',
      'Visa Application Lodgement & Tracking',
    ],
  },
  'pre-departure-assistance': {
    title: 'Pre-departure Support',
    subtitle: 'Comprehensive orientation from accommodation booking to arrival support',
    metaTitle: 'Pre-departure Support | 13 Dreams Consultants',
    metaDesc: 'Briefing sessions on culture, accommodation bookings, transit arrangements, foreign exchange cards, and what to pack.',
    overview: 'Briefing sessions on culture, accommodation bookings, transit arrangements, foreign exchange cards, and what to pack. We ensure every student leaves India fully prepared and confident.',
    keyOfferings: [
      'Comprehensive pre-departure briefing sessions (country culture, weather, transport, cuisine).',
      'On-campus and off-campus accommodation booking and lease agreement review.',
      'Multi-currency forex card setup and travel insurance enrollment.',
      'Flight booking assistance with student fare verification.',
      'Airport pickup coordination and city orientation guide delivery.',
    ],
    processSteps: [
      'Pre-Departure Briefing Session',
      'Accommodation Research & Booking',
      'Forex Card & Travel Insurance Setup',
      'Flight Booking & Luggage Advice',
      'Arrival & Pick-up Coordination',
    ],
  },
  'value-added-services': {
    title: 'Value Added Services',
    subtitle: 'SIM cards, banking, forex, and airport support for a seamless arrival',
    metaTitle: 'Value Added Services | 13 Dreams Consultants',
    metaDesc: 'SIM cards, student bank account setup assistance, forex transfers, and airport pickup arrangements with overseas partner bodies.',
    overview: 'SIM cards, student bank account setup assistance, forex transfers, and airport pickup arrangements with overseas partner bodies. Our value-added services eliminate every logistical friction point.',
    keyOfferings: [
      'International student SIM cards activated prior to departure from India with generous data packs.',
      'Zero-balance student bank account opening (Canada GIC accounts, German Blocked accounts, UK student accounts).',
      'Comprehensive travel and medical insurance with cashless hospital coverage.',
      'Coordinated airport pickup services and temporary transit hotel bookings.',
    ],
    processSteps: [
      'Identification of Post-Visa Logistics Requirements',
      'Connecting with Banking & Forex Service Partners',
      'Pre-activation of Telecom SIM Cards & Multi-Currency Cards',
      'Delivery of All Travel Kits & Airport Pickup Vouchers',
    ],
  },
  'visa-counseling': {
    title: 'Visa Counseling',
    subtitle: 'Strategic profile evaluation, tackling study gaps, and managing previous refusal cases',
    metaTitle: 'Visa Counseling | 13 Dreams Consultants',
    metaDesc: 'Tailored visa risk assessment, gap year justification, previous refusal case rectifications, and embassy compliance counseling by 13 Dreams.',
    overview: 'Every student profile is unique, carrying individual strengths as well as potential challenges such as study gaps, career shifts, backlogs, or even previous visa refusals. Our senior visa counseling wing conducts an honest, forensic audit of your credentials to design a robust justification strategy that satisfies visa officers\' stringent scrutiny.',
    keyOfferings: [
      'Comprehensive assessment of past study gaps and employment history verification.',
      'Refusal case analysis (ATIP / CAIPS notes interpretation for Canada, UK refusal reviews).',
      'Strong justification letter drafting for career transitions or second Master\'s degrees.',
      'Financial source verification to ensure all funds meet embassy anti-money-laundering audits.',
    ],
    processSteps: [
      'Full Profile Audit & Risk Identification',
      'Gathering Supplementary Affidavits & Experience Credentials',
      'Drafting Strategic SOP Addressing Previous Weaknesses',
      'Re-application Lodgement with Impeccable Supporting Proofs',
    ],
  },
  'visa-processing': {
    title: 'Visa Processing',
    subtitle: 'Accurate online filing, portal documentation uploads, and real-time tracking',
    metaTitle: 'Visa Processing | 13 Dreams Consultants',
    metaDesc: 'Flawless online visa submission on official High Commission portals with document compliance and tracking by 13 Dreams Consultants.',
    overview: 'Electronic visa filing requires precision. Uploading improperly scanned documents, misclassifying family details, or misinterpreting portal prompts can lead to lengthy procedural delays. Our visa processing team handles official immigration portals (IRCC, ImmiAccount, UKVI, CEAC) day in and day out, ensuring your application is lodged flawlessly.',
    keyOfferings: [
      'Portal form filling across IRCC (Canada), ImmiAccount (Australia), UKVI (UK), and US CEAC.',
      'High-resolution document scanning, compression, and compliance verification.',
      'Payment handling for government visa application fees through secure gateways.',
      'Immediate biometric and medical exam slot booking at nearest VFS centers.',
      'Active status monitoring and prompt responses to embassy requests for additional information.',
    ],
    processSteps: [
      'Pre-Filing Document Cross-Verification',
      'Official Government Visa Portal Form Completion',
      'Document Uploading, Compression & Validation',
      'Submission, Fee Payment & Acknowledgement Receipt Generation',
      'Biometric Appointment Scheduling & Final Visa Tracking',
    ],
  },
  'admission-assistance': {
    title: 'Admission Assistance',
    subtitle: 'Direct university tie-ups enabling fast offer letters and CAS/COE issuances',
    metaTitle: 'Admission Assistance | 13 Dreams Consultants',
    metaDesc: 'Direct university tie-ups enabling application fee waivers, rapid offer letters, and prompt CAS / COE issuances.',
    overview: 'Direct university tie-ups enabling application fee waivers, rapid offer letters, and prompt CAS / COE issuances. Our established institutional relationships accelerate your path from application to unconditional offer.',
    keyOfferings: [
      'Application fee waivers through direct university partner agreements.',
      'Priority processing lanes at 150+ partner universities globally.',
      'Rapid unconditional offer letter procurement within 3 to 7 business days.',
      'CAS (UK), COE (Australia), and LOA (Canada) verification and acceptance support.',
    ],
    processSteps: [
      'University Tie-Up Verification & Fee Waiver Enrollment',
      'Priority Application Submission',
      'Offer Letter Receipt & Conditions Clearance',
      'CAS/COE Issuance & Final Visa Preparation',
    ],
  },
  'finance-assistance': {
    title: 'Finance Assistance',
    subtitle: 'Structured education loans, fund verification, and financial documentation',
    metaTitle: 'Finance Assistance | Education Loans | 13 Dreams Consultants',
    metaDesc: 'Collateral and non-collateral education loan guidance through nationalized and private banking partners with 13 Dreams Consultants.',
    overview: 'Satisfying embassy financial proof rules is often the most critical hurdle in obtaining a study visa. Whether embassies demand 28-day funds (UK), GIC certificates (Canada), Blocked Accounts (Germany), or genuine bank loans (USA/Australia), our finance advisory wing guides parents and students on acceptable sponsorship structures that meet strict immigration compliance.',
    keyOfferings: [
      'Partnerships with nationalized banks (SBI, PNB, BOB) and premier private lenders (HDFC Credila, ICICI, Avanse).',
      'Assistance with collateral-free (unsecured) education loans up to ₹50-75 Lakhs.',
      'Guidance on acceptable co-signers, IT returns, and property evaluation reports.',
      'Speedy loan sanction letters directly acceptable by overseas universities and embassies.',
    ],
    processSteps: [
      'Initial Financial Assessment & Budget Calculation',
      'Bank Matching Based on Tuition Fees & Student Profile',
      'Document Submission & Income Verification',
      'Loan Sanction Letter Issuance & Direct University Disbursement',
    ],
  },
  'scholarship-guidance': {
    title: 'Scholarship Guidance',
    subtitle: 'Unlocking merit scholarships, early bird discounts, and government grants',
    metaTitle: 'Scholarship Guidance | 13 Dreams Consultants',
    metaDesc: 'Dedicated guidance for securing merit-based international scholarships, regional bursaries, and tuition fee reductions with 13 Dreams Consultants.',
    overview: 'Studying overseas is an invaluable investment, and securing financial awards makes it significantly more viable. Our scholarship guidance desk works closely with candidates from the very first counseling session to position their academic and extracurricular achievements effectively for competitive university scholarships and external grants.',
    keyOfferings: [
      'Comprehensive listing of early-bird discounts and regional diversity scholarships.',
      'Targeted statement of purpose coaching highlighting leadership, research, and community involvement.',
      'Review of external scholarship programs (Fulbright, Erasmus Mundus, DAAD, Australia Awards).',
      'Direct coordination with university admissions panels to advocate for candidate bursaries.',
    ],
    processSteps: [
      'Scholarship Eligibility Screening',
      'Application Window & Deadline Mapping',
      'Essay Formulation & Academic Recommendation Optimization',
      'Official Scholarship Application Lodgement & Award Confirmation',
    ],
  },
  'study-visa-consultants-bareilly': {
    title: 'Study Visa Consultants Bareilly',
    subtitle: 'Your premier overseas education and immigration consultancy in Bareilly & North India',
    metaTitle: 'Study Visa Consultants Bareilly | 13 Dreams Consultants',
    metaDesc: 'Best study visa consultants in Bareilly at Luthra Tower, Ekta Nagar. 15+ years of trusted visa guidance for Canada, UK, Australia, USA, and Germany.',
    overview: 'Located at Luthra Tower, 2nd Floor, C-56 Ekta Nagar, Opp. LIC Office, Model Town, Bareilly, 13 Dreams Consultants Private Limited is widely recognized as the top visa consultancy in the region. For over 15 years, our senior leadership and certified counseling staff have empowered thousands of students across Bareilly, Moradabad, Rampur, Shahjahanpur, Pilibhit, and Uttarakhand to achieve their global study ambitions.',
    keyOfferings: [
      'Prime Bareilly branch office easily accessible in Model Town, Ekta Nagar.',
      'Over 15 years of industry authority and thousands of verified student visa grants.',
      'Complete end-to-end guidance under one roof: IELTS/PTE training, course selection, admissions, visa filing, and education loans.',
      'Regular in-person visits by foreign university representatives for on-the-spot assessments.',
      'High client satisfaction rating and transparent, ethical fee structures.',
    ],
    processSteps: [
      'Walk-in or Book a Free Counseling Appointment at Our Bareilly Office',
      'Profile Assessment with Mr. Harpreet Singh and Senior Advisory Team',
      'Fast-Track University Application & Offer Letter Issuance',
      'Rigorous Visa Dossier Preparation & Mock Interviews',
      'Successful Visa Grant & Pre-Departure Farewell',
    ],
  },
};

export const countryPageData = {
  australia: {
    countryName: 'Australia',
    tagline: 'World-Class Education, High Living Standards, and Generous Post-Study Work Visas',
    bannerImg: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1200&q=80',
    metaTitle: 'Study in Australia | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Complete guidance for Indian students to study in Australia. Learn about universities, courses, Subclass 500 visa, scholarships, and post-study work rights.',
    overview: 'Australia has a well-deserved reputation as one of the leading educational destinations. It is the world\'s third most popular destination for international students. Australian universities are globally recognized for excellence in research, innovation, and industry-oriented training. With vibrant multicultural cities like Melbourne, Sydney, Brisbane, and Perth, students enjoy exceptional quality of life and career exposure.',
    whyStudyPoints: [
      'Globally Ranked Institutions: 7 of the world\'s top 100 universities belong to Group of Eight (Go8).',
      'Post-Study Work Rights: Subclass 485 Temporary Graduate Visa provides 2 to 4 years of open work authorization.',
      'Part-Time Work Permission: Work up to 48 hours per fortnight during study terms and unlimited hours during vacations.',
      'Extensive Scholarships: Australian Awards and institutional merit fee reductions ranging from 15% to 50%.',
      'Simplified Student Visa (Subclass 500): Streamlined online lodgement with transparent financial requirements.',
    ],
    topUniversities: [
      'University of Melbourne', 'University of Sydney', 'UNSW Sydney', 'Monash University',
      'University of Queensland', 'Deakin University', 'RMIT University', 'La Trobe University',
    ],
    visaFacts: [
      'Subclass 500 Student Visa with genuine student assessment.',
      'Minimum IELTS score of 6.0 - 6.5 (or PTE equivalent of 50 - 58).',
      'Overseas Student Health Cover (OSHC) mandatory for entire duration.',
      '13 Dreams Bareilly & Khatima offices offer complete GTE documentation assistance.',
    ],
  },
  canada: {
    countryName: 'Canada',
    tagline: 'Diverse Society, World-Class Universities, and a Clear Pathway to Permanent Residency',
    bannerImg: 'https://images.unsplash.com/photo-1517090504586-fde19ea6066f?auto=format&fit=crop&w=1200&q=80',
    metaTitle: 'Study in Canada | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Study in Canada with 13 Dreams Consultants. Get expert guidance on universities, student visas, SDS applications, and PR pathways for Indian students.',
    overview: 'Canada has been rated the world\'s third-best country for education. The country\'s cost of living is lower than most English-speaking nations, and its warm multicultural society ensures outstanding social integration for Indian students. Canada\'s Express Entry and Provincial Nominee Programs (PNPs) create some of the most accessible permanent residency pathways available globally.',
    whyStudyPoints: [
      'Post-Graduation Work Permit (PGWP): Up to 3 years of open work permit tied to degree duration.',
      'Express Entry PR: Accumulate Canadian work experience toward permanent residency within 2 to 3 years.',
      'Student Direct Stream (SDS): Accelerated student visa for top academic performers.',
      'Low Cost vs. USA/UK: Tuition fees at top Canadian universities cost 20% to 30% less than comparable UK/US institutions.',
      'Bilingual Culture: Thriving French-speaking communities in Montreal and Quebec open doors to unique career advantages.',
    ],
    topUniversities: [
      'University of Toronto', 'University of British Columbia (UBC)', 'McGill University',
      'University of Alberta', 'University of Waterloo', 'Ryerson University',
      'George Brown College', 'Humber College',
    ],
    visaFacts: [
      'Canadian Study Permit from IRCC (Immigration, Refugees and Citizenship Canada).',
      'GIC (Guaranteed Investment Certificate) of CAD 10,000 required for SDS applicants.',
      'Minimum IELTS 6.0 overall for most universities.',
      'SDS stream guarantees processing within 20 business days for qualified applicants.',
    ],
  },
  uk: {
    countryName: 'UK',
    tagline: 'Prestigious 1-Year Master\'s Degrees, Graduate Route Visa, and World Heritage Academia',
    bannerImg: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80',
    metaTitle: 'Study in UK | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Study in the UK with expert guidance on Russell Group universities, Student Visa (Tier 4), Graduate Route, and IELTS requirements from 13 Dreams Consultants.',
    overview: 'The United Kingdom, or Great Britain, has been regarded as a hub of knowledge and quality education for centuries. With prestigious institutions such as Oxford, Cambridge, Imperial College, and the London School of Economics, a UK degree carries unmatched global prestige. One-year Master\'s programs save both time and money while the new Graduate Route Visa allows 2 years of post-study work.',
    whyStudyPoints: [
      'World-Renowned Institutions: Oxford, Cambridge, Imperial College — top 10 globally ranked universities.',
      '1-Year Master\'s Degrees: Save one full academic year of tuition and living costs vs. Australian/Canadian counterparts.',
      'Graduate Route Visa: 2 years of work authorization after Bachelor\'s, 3 years after Master\'s or PhD.',
      'Multicultural Cities: London, Manchester, Birmingham host vibrant Indian student communities.',
      'Pathway to Settlement: 5-year residency route available for eligible graduates securing skilled employment.',
    ],
    topUniversities: [
      'University of Oxford', 'University of Cambridge', 'Imperial College London',
      'University College London (UCL)', 'University of Edinburgh', 'University of Manchester',
      'University of Birmingham', 'Coventry University',
    ],
    visaFacts: [
      'UK Student Visa (previously Tier 4) with CAS from a licensed sponsor university.',
      '28-day bank balance requirement (tuition fees + £1,334/month for London living).',
      'Minimum IELTS 6.0-6.5 (UKVI-approved test center only).',
      '13 Dreams provides complete CAS verification and financial documentation support.',
    ],
  },
  usa: {
    countryName: 'USA',
    tagline: 'Home to the World\'s Top Research Universities and the Largest International Student Ecosystem',
    bannerImg: 'https://images.unsplash.com/photo-1485738422979-f5c462d49f74?auto=format&fit=crop&w=1200&q=80',
    metaTitle: 'Study in USA | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Study in the USA with 13 Dreams Consultants. Complete F-1 visa guidance, I-20 processing, OPT/STEM OPT extension advice, and top university applications.',
    overview: 'The majority of students across the world dream about studying in the United States, which tops the list of the 10 most popular countries for global academia. Home to Harvard, MIT, Stanford, Caltech, and over 4,000 accredited institutions, the USA offers unprecedented academic breadth across STEM, business, arts, and humanities with the globally coveted F-1 Student Visa pathway.',
    whyStudyPoints: [
      'World\'s No. 1 Education Destination: 8 of the global Top 10 universities reside in the USA.',
      'OPT (Optional Practical Training): 1 year of post-study work with 3-year STEM OPT extension.',
      'Research & Funding Opportunities: Extensive TA and RA stipend positions for postgraduate students.',
      'Campus Diversity: A rich multicultural environment with India being the largest source country of international students.',
      'Career Networking: Access to Silicon Valley, Wall Street, and Fortune 500 corporate recruiting networks.',
    ],
    topUniversities: [
      'Massachusetts Institute of Technology (MIT)', 'Stanford University', 'Harvard University',
      'California Institute of Technology (Caltech)', 'University of Chicago',
      'University of California, Berkeley', 'Carnegie Mellon University', 'Purdue University',
    ],
    visaFacts: [
      'F-1 Student Visa with I-20 from a SEVP-certified institution.',
      'SEVIS (Student Exchange Visitor Information System) fee payment required.',
      'Embassy interview mandatory — 13 Dreams provides mock interview prep.',
      'Maintain full-time enrollment status as per F-1 regulations.',
    ],
  },
  'new-zealand': {
    countryName: 'New Zealand',
    tagline: 'Peaceful Living, High Quality Education, and Strong Post-Study Work Rights',
    bannerImg: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1200&q=80',
    metaTitle: 'Study in New Zealand | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Study in New Zealand with 13 Dreams Consultants. Expert guidance on student visas, top universities, partner and post-study work rights.',
    overview: 'New Zealand is a gorgeous, safe, and welcoming country consistently ranked among the world\'s most peaceful nations. Its universities are internationally accredited and offer modern, research-oriented programs. New Zealand\'s post-study work rights and partner open work permits add significant financial value to an already affordable study destination.',
    whyStudyPoints: [
      'Post Study Work Visa: Up to 3 years of open work authorization depending on study level and institution.',
      'Paid Work Rights: Work 20 hours per week during term and full-time during breaks.',
      'Partner Work Rights: Full-time open work permit for spouses of students pursuing Master\'s degrees in Green List areas.',
      'Peaceful & Safe: Ranked consistently among the top 3 most peaceful nations in the Global Peace Index.',
    ],
    topUniversities: [
      'University of Auckland', 'University of Otago', 'Victoria University of Wellington',
      'University of Canterbury', 'Massey University', 'University of Waikato',
      'Lincoln University', 'Auckland University of Technology (AUT)',
    ],
    visaFacts: [
      'Fee Paying Student Visa with transparent fund verification.',
      'Payment of tuition fees only required AFTER Approval in Principle (AIP).',
      'Special assistance with Immigration New Zealand (INZ) documentation at 13 Dreams.',
    ],
  },
  germany: {
    countryName: 'Germany',
    tagline: 'Tuition-Free Education, Europe\'s Largest Economy, and 18 Months Post-Study Work Visas',
    bannerImg: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80',
    metaTitle: 'Study in Germany | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Explore tuition-free universities, English-taught Master\'s degrees, APS certificate processing, and 18-month job seeker visas in Germany with 13 Dreams Consultants.',
    overview: 'There is so much more Germany has to offer to international students. Tuition fees are negligible in public universities, while academic standards in mechanical engineering, computer science, automotive design, and renewable energy are world-leading. Graduating from a German university opens direct doors to high-paying careers across the European Union with streamlined EU Blue Card permanent residency pathways.',
    whyStudyPoints: [
      'Zero Tuition Fees: Most public universities charge only a nominal administration fee (€150 to €350 per semester).',
      '18-Month Job Seeker Visa: Upon graduation, students receive 1.5 years to secure employment matching their degree.',
      'English-Taught Degrees: Over 1,500 Master\'s programs conducted completely in English.',
      'Strongest European Economy: Europe\'s industrial hub with acute demand for IT engineers, data scientists, and technicians.',
      'Part-Time Work: Allowed to work 140 full days or 280 half days per calendar year.',
    ],
    topUniversities: [
      'Technical University of Munich (TUM)', 'RWTH Aachen University', 'TU Berlin',
      'University of Stuttgart', 'Karlsruhe Institute of Technology (KIT)', 'Heidelberg University',
      'IU International University of Applied Sciences', 'SRH Berlin University of Applied Sciences',
    ],
    visaFacts: [
      'National Student Visa (Type D) with Blocked Account (Sperrkonto).',
      'Mandatory APS (Akademische Prüfstelle) certificate required for Indian applicants.',
      'Health insurance verification via TK, Barmer, or Coracle.',
      'End-to-end blocked account and APS submission assistance provided by 13 Dreams team.',
    ],
  },
  malta: {
    countryName: 'Malta',
    tagline: 'Schengen Visa Privileges, English-Speaking Culture, and Affordable European Education',
    bannerImg: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=1200&q=80',
    metaTitle: 'Study in Malta | Schengen Visa & English-Taught Degrees | 13 Dreams',
    metaDesc: 'Study in Malta with European Schengen access, affordable tuition, and English-speaking education with 13 Dreams Consultants.',
    overview: 'Malta is one of the world\'s most tranquil and scenic island countries, providing a great atmosphere for overseas students. As an English-speaking member of the European Union and the Schengen Zone, Malta delivers superb British-patterned education at tuition costs substantially lower than the UK or Western Europe, all while providing visa-free access across 27 European nations.',
    whyStudyPoints: [
      'Schengen Area Member: Travel freely across 27 European nations during study breaks.',
      'English-Speaking Nation: English is an official language spoken by 90% of the population.',
      'Affordable Tuition Fees: Degrees starting from €5,000 to €8,500 per academic year.',
      'Part-Time Work Permission: International students can work 20 hours per week after the 90th day of stay.',
      'Post-Study Residence: Job search residency permits available for tertiary degree graduates.',
    ],
    topUniversities: [
      'University of Malta', 'MCAST (Malta College of Arts, Science and Technology)',
      'Global College Malta', 'London School of Commerce Malta',
      'American University of Malta', 'Domain Academy Malta',
    ],
    visaFacts: [
      'National Long Stay (Type D) Schengen Student Visa.',
      'Simplified documentation without stringent financial block requirements.',
      'Fast visa processing times with strong approval rates through 13 Dreams.',
    ],
  },
  singapore: {
    countryName: 'Singapore',
    tagline: 'Asia\'s Premier Financial & Tech Capital, High Global Safety, and World-Class Universities',
    bannerImg: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80',
    metaTitle: 'Study in Singapore | Asian Global Education Hub | 13 Dreams',
    metaDesc: 'Study in Singapore. World-class Asian business hub, international university branch campuses, and fast-track diplomas with 13 Dreams Consultants.',
    overview: 'Singapore\'s education system is considered world-class. The degrees provided at world universities\' Singapore campuses offer top Asian industry exposure and international recognition. Positioned as the financial hub of Asia, Singapore hosts multinational corporate headquarters, providing extraordinary networking, internships, and high employment stability.',
    whyStudyPoints: [
      'Global Financial & Technology Hub: High concentration of global Fortune 500 regional headquarters.',
      'International University Branch Campuses: Earn Australian or UK degrees at significantly reduced living expenses.',
      'High Standards of Safety: Rated the safest city in the world with exceptional public transit and infrastructure.',
      'No IELTS Options: Multiple institutions offer internal English proficiency placement tests.',
      'Fast Admission & Student Pass: Transparent, streamlined Solar+ visa processing with no Embassy interview.',
    ],
    topUniversities: [
      'National University of Singapore (NUS)', 'Nanyang Technological University (NTU)',
      'Singapore Management University (SMU)', 'James Cook University Singapore',
      'Curtin Singapore', 'PSB Academy', 'Kaplan Higher Education Academy Singapore', 'MDIS Singapore',
    ],
    visaFacts: [
      'Student\'s Pass (STP) issued directly via Singapore Immigration & Checkpoints Authority (ICA).',
      'Fast turnaround of 2 to 4 weeks.',
      'Bank balance required only for standard living expenses with no long seasoning restrictions.',
    ],
  },
  ireland: {
    countryName: 'Ireland',
    tagline: 'European Silicon Valley, 2-Year Post-Study Work Visas, and World-Renowned Research Universities',
    bannerImg: 'https://images.unsplash.com/photo-1549918864-48ac978761a4?auto=format&fit=crop&w=1200&q=80',
    metaTitle: 'Study in Ireland | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Study in Ireland with 13 Dreams Consultants. Learn about Trinity College, UCD, Third Level Graduate Scheme (2-year work permit), and European tech hub careers.',
    overview: 'Ireland is Europe’s primary technology and pharmaceutical hub, hosting European headquarters of Google, Apple, Meta, Microsoft, and Pfizer. As an English-speaking country in the European Union, Ireland combines historic academic institutions with forward-looking industry internships, making it one of the most popular and financially rewarding study destinations for Indian students.',
    whyStudyPoints: [
      'European Tech Capital: Dublin is home to European headquarters for top global tech, finance, and biotech corporations.',
      'Third Level Graduate Scheme: Up to 2 years of open post-study work authorization for Master’s graduates.',
      'English-Speaking EU Member: Smooth cultural integration and unrestricted European career connections.',
      'Affordable Tuition Fees: Highly competitive tuition costs compared to the US and UK.',
      'Part-Time Work Permission: Work up to 20 hours per week during term and 40 hours during holidays.',
    ],
    topUniversities: [
      'Trinity College Dublin (TCD)', 'University College Dublin (UCD)', 'University of Galway',
      'University College Cork (UCC)', 'Dublin City University (DCU)', 'University of Limerick',
      'Maynooth University', 'Technological University Dublin (TU Dublin)',
    ],
    visaFacts: [
      'Irish Student Visa (Stamp 2) with valid acceptance and proof of funds.',
      'Minimum IELTS requirement typically 6.0 - 6.5 overall.',
      'Private medical insurance is mandatory for international students.',
      'End-to-end documentation scrutiny and visa lodgement with 13 Dreams Bareilly.',
    ],
  },
  switzerland: {
    countryName: 'Switzerland',
    tagline: 'World Capital of Hospitality, Elite Scientific Research, and Exceptional Quality of Life',
    bannerImg: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80',
    metaTitle: 'Study in Switzerland | Hospitality & Top Universities | 13 Dreams',
    metaDesc: 'Explore studying in Switzerland with 13 Dreams Consultants. Global leader in hospitality management, ETH Zurich, cutting-edge science, and high living standards.',
    overview: 'Switzerland is world-renowned for its pristine natural beauty, exceptional safety, and unparalleled global reputation in hospitality management, banking, luxury brand administration, and scientific research. Home to ETH Zurich and the world’s most prestigious hotel schools, Switzerland offers international students an elite learning environment and global executive career pathways.',
    whyStudyPoints: [
      'Global Leader in Hospitality: Home to top-ranked hotel and luxury management schools worldwide.',
      'World-Class Research: Institutions like ETH Zurich consistently rank among the top 10 universities globally.',
      'Paid Industry Internships: Hospitality programs typically include structured, high-paying Swiss internships.',
      'Heart of Europe: Central Schengen location allows seamless travel across all European capitals.',
      'Pristine Living & Safety: Consistently ranked at the pinnacle of global happiness and safety indices.',
    ],
    topUniversities: [
      'ETH Zurich', 'EPFL (Lausanne)', 'University of Zurich', 'University of Geneva',
      'EHL Hospitality Business School', 'Glion Institute of Higher Education',
      'Les Roches Global Hospitality Education', 'Swiss Hotel Management School (SHMS)',
    ],
    visaFacts: [
      'Swiss National Visa (Type D) for long-term academic studies.',
      'Evidence of financial capability and accommodation confirmation required.',
      'Clear motivation statement and educational credential apostille.',
      'Complete embassy file review and preparation by 13 Dreams senior team.',
    ],
  },
};

