// ==========================================
// lib/pageData.js
// Centralised detail data for dynamic routes
// /service/[slug] and /study/[slug]
// ==========================================

export const servicePageData = {
  'comprehensive-counselling': {
    title: 'Comprehensive Counselling',
    subtitle: 'Personalized, unbiased academic and career mapping for international aspirants',
    metaTitle: 'Comprehensive Counselling | 13 Dreams Consultants',
    metaDesc: 'Expert course and career counseling for students planning to study abroad. One-on-one guidance based on academic profile, budget, and long-term career goals.',
    overview: 'We have professional counsellors who are experienced in effectively assisting students in their course and country of study selection. Navigating through thousands of international universities, varying admission prerequisites, and career outcomes can be overwhelming. Our comprehensive counseling evaluates your academic transcripts, aptitude, budget limitations, and post-graduation goals to craft a customized roadmap.',
    keyOfferings: [
      'One-on-one profiling assessment by senior study abroad advisors.',
      'Shortlisting of best-fit countries (Canada, UK, Australia, USA, Germany, NZ, Singapore, Malta).',
      'In-depth comparative analysis of tuition fees, cost of living, and part-time earning opportunities.',
      'Clear guidance on test requirements (IELTS, PTE, TOEFL, GRE, GMAT, Duolingo).',
      'Discussion of post-study work permits (PGWP, Subclass 485, Graduate Route) and PR opportunities.',
    ],
    processSteps: [
      'Initial Profile Review & Academic Assessment',
      'Course, Major, and Specialization Identification',
      'Shortlisting 3 to 5 Best-Fit Foreign Universities',
      'Budgeting, Fee Schedules, and Scholarship Probability Assessment',
      'Creation of a Month-by-Month Application Action Plan',
    ],
  },
  'application-processing': {
    title: 'Application Processing',
    subtitle: 'Expert-managed university admissions from shortlisting to offer letter',
    metaTitle: 'Application Processing | 13 Dreams Consultants',
    metaDesc: 'Streamlined university application processing, document submission, and offer letter procurement by 13 Dreams Consultants.',
    overview: 'Students often find the application process to be intimidating. Hence our team of skilled counsellors provides extensive hand-holding to help them submit polished and complete applications that maximize their offer letter success rate.',
    keyOfferings: [
      'Shortlisting universities matching academic merit, IELTS/PTE scores, and budget.',
      'Preparation of personal statements, letters of intent, and academic references.',
      'Online application filing on official university portals with document uploads.',
      'Following up directly with university admissions teams for faster processing.',
      'Procurement and verification of official offer letters and Confirmation of Acceptance (CAS/COE).',
    ],
    processSteps: [
      'University Shortlisting & Gap Analysis',
      'SOP & Reference Letter Drafting',
      'Online Application Submission',
      'Offer Letter & Unconditional Acceptance Procurement',
      'Admission Confirmation & Visa Stage Handover',
    ],
  },
  'advice-on-program-selection': {
    title: 'Advice on Selection of Programs',
    subtitle: 'Data-driven course matching based on academics, careers, and market demand',
    metaTitle: 'Advice on Program Selection | 13 Dreams Consultants',
    metaDesc: 'Professional guidance on selecting the right international program and specialization for your academic profile and career goals.',
    overview: 'We maintain frequent contact with the colleges we represent and remain up to speed on the various courses and programs of study they provide. Our advisors analyze global job markets to ensure your chosen program has strong employment outcomes.',
    keyOfferings: [
      'Comprehensive database of 150+ partner universities and their top programs.',
      'Matching your undergraduate stream to globally in-demand postgraduate specializations.',
      'Career outcomes research: average salaries, PR eligibility, and job placement rates.',
      'Guidance on bridging programs for career changers entering new disciplines abroad.',
    ],
    processSteps: [
      'Academic Transcript & Stream Review',
      'Career Goal Mapping & Market Analysis',
      'Program Universe Shortlisting',
      'Final Program Lock-in & Application Action Plan',
    ],
  },
  'assistance-with-scholarship-applications': {
    title: 'Scholarship Application Assistance',
    subtitle: 'Identifying and securing financial awards to ease your study abroad costs',
    metaTitle: 'Scholarship Application Assistance | 13 Dreams Consultants',
    metaDesc: 'Identify and secure university scholarships and bursaries that lighten the financial load of international higher studies.',
    overview: 'Identify and secure university scholarships and bursaries that lighten the financial load of international higher studies. We proactively research and advocate for merit and diversity scholarship awards at every partner institution.',
    keyOfferings: [
      'Comprehensive research across university merit scholarships, regional bursaries, and diversity grants.',
      'Early bird discount identification and application window tracking.',
      'Scholarship essay and statement of purpose coaching.',
      'Direct advocacy with university admissions panels for fee reduction consideration.',
    ],
    processSteps: [
      'Scholarship Eligibility Screening',
      'Application Window & Deadline Mapping',
      'Essay Formulation & Academic Recommendation Optimization',
      'Official Scholarship Application Lodgement & Award Confirmation',
    ],
  },
  'advice-on-student-visas': {
    title: 'Student Visa Guidance',
    subtitle: 'End-to-end visa documentation, financial proof, and mock interview preparation',
    metaTitle: 'Student Visa Guidance | 13 Dreams Consultants',
    metaDesc: 'End-to-end documentation scrutiny, financial sponsorship arrangement verification, and mock interview preparations for high visa success.',
    overview: 'End-to-end documentation scrutiny, financial sponsorship arrangement verification, and mock interview preparations for high visa success. Our visa team has maintained a 99% visa approval track record through meticulous compliance.',
    keyOfferings: [
      'Country-specific visa documentation checklists (Canada, UK, Australia, USA, Germany, NZ, Singapore, Malta).',
      'Financial sponsorship structure audits: bank balance, loan letters, GIC certificates, and blocked accounts.',
      'Statement of Purpose (SOP) drafting, review, and iteration cycles.',
      'Mock visa officer interviews and difficult question simulation practice.',
      'Post-submission tracking and prompt responses to embassy Requests for Further Information (RFI).',
    ],
    processSteps: [
      'Visa Documentation Checklist Review',
      'Financial Proof Assembly & Bank Statement Guidance',
      'SOP & Cover Letter Drafting',
      'Mock Interview Preparation & Final Document Verification',
      'Visa Application Lodgement & Tracking',
    ],
  },
  'pre-departure-assistance': {
    title: 'Pre-departure Support',
    subtitle: 'Comprehensive orientation from accommodation booking to arrival support',
    metaTitle: 'Pre-departure Support | 13 Dreams Consultants',
    metaDesc: 'Briefing sessions on culture, accommodation bookings, transit arrangements, foreign exchange cards, and what to pack.',
    overview: 'Briefing sessions on culture, accommodation bookings, transit arrangements, foreign exchange cards, and what to pack. We ensure every student leaves India fully prepared and confident.',
    keyOfferings: [
      'Comprehensive pre-departure briefing sessions (country culture, weather, transport, cuisine).',
      'On-campus and off-campus accommodation booking and lease agreement review.',
      'Multi-currency forex card setup and travel insurance enrollment.',
      'Flight booking assistance with student fare verification.',
      'Airport pickup coordination and city orientation guide delivery.',
    ],
    processSteps: [
      'Pre-Departure Briefing Session',
      'Accommodation Research & Booking',
      'Forex Card & Travel Insurance Setup',
      'Flight Booking & Luggage Advice',
      'Arrival & Pick-up Coordination',
    ],
  },
  'value-added-services': {
    title: 'Value Added Services',
    subtitle: 'SIM cards, banking, forex, and airport support for a seamless arrival',
    metaTitle: 'Value Added Services | 13 Dreams Consultants',
    metaDesc: 'SIM cards, student bank account setup assistance, forex transfers, and airport pickup arrangements with overseas partner bodies.',
    overview: 'SIM cards, student bank account setup assistance, forex transfers, and airport pickup arrangements with overseas partner bodies. Our value-added services eliminate every logistical friction point.',
    keyOfferings: [
      'International student SIM cards activated prior to departure from India with generous data packs.',
      'Zero-balance student bank account opening (Canada GIC accounts, German Blocked accounts, UK student accounts).',
      'Comprehensive travel and medical insurance with cashless hospital coverage.',
      'Coordinated airport pickup services and temporary transit hotel bookings.',
    ],
    processSteps: [
      'Identification of Post-Visa Logistics Requirements',
      'Connecting with Banking & Forex Service Partners',
      'Pre-activation of Telecom SIM Cards & Multi-Currency Cards',
      'Delivery of All Travel Kits & Airport Pickup Vouchers',
    ],
  },
  'visa-counseling': {
    title: 'Visa Counseling',
    subtitle: 'Strategic profile evaluation, tackling study gaps, and managing previous refusal cases',
    metaTitle: 'Visa Counseling | 13 Dreams Consultants',
    metaDesc: 'Tailored visa risk assessment, gap year justification, previous refusal case rectifications, and embassy compliance counseling by 13 Dreams.',
    overview: 'Every student profile is unique, carrying individual strengths as well as potential challenges such as study gaps, career shifts, backlogs, or even previous visa refusals. Our senior visa counseling wing conducts an honest, forensic audit of your credentials to design a robust justification strategy that satisfies visa officers\' stringent scrutiny.',
    keyOfferings: [
      'Comprehensive assessment of past study gaps and employment history verification.',
      'Refusal case analysis (ATIP / CAIPS notes interpretation for Canada, UK refusal reviews).',
      'Strong justification letter drafting for career transitions or second Master\'s degrees.',
      'Financial source verification to ensure all funds meet embassy anti-money-laundering audits.',
    ],
    processSteps: [
      'Full Profile Audit & Risk Identification',
      'Gathering Supplementary Affidavits & Experience Credentials',
      'Drafting Strategic SOP Addressing Previous Weaknesses',
      'Re-application Lodgement with Impeccable Supporting Proofs',
    ],
  },
  'visa-processing': {
    title: 'Visa Processing',
    subtitle: 'Accurate online filing, portal documentation uploads, and real-time tracking',
    metaTitle: 'Visa Processing | 13 Dreams Consultants',
    metaDesc: 'Flawless online visa submission on official High Commission portals with document compliance and tracking by 13 Dreams Consultants.',
    overview: 'Electronic visa filing requires precision. Uploading improperly scanned documents, misclassifying family details, or misinterpreting portal prompts can lead to lengthy procedural delays. Our visa processing team handles official immigration portals (IRCC, ImmiAccount, UKVI, CEAC) day in and day out, ensuring your application is lodged flawlessly.',
    keyOfferings: [
      'Portal form filling across IRCC (Canada), ImmiAccount (Australia), UKVI (UK), and US CEAC.',
      'High-resolution document scanning, compression, and compliance verification.',
      'Payment handling for government visa application fees through secure gateways.',
      'Immediate biometric and medical exam slot booking at nearest VFS centers.',
      'Active status monitoring and prompt responses to embassy requests for additional information.',
    ],
    processSteps: [
      'Pre-Filing Document Cross-Verification',
      'Official Government Visa Portal Form Completion',
      'Document Uploading, Compression & Validation',
      'Submission, Fee Payment & Acknowledgement Receipt Generation',
      'Biometric Appointment Scheduling & Final Visa Tracking',
    ],
  },
  'admission-assistance': {
    title: 'Admission Assistance',
    subtitle: 'Direct university tie-ups enabling fast offer letters and CAS/COE issuances',
    metaTitle: 'Admission Assistance | 13 Dreams Consultants',
    metaDesc: 'Direct university tie-ups enabling application fee waivers, rapid offer letters, and prompt CAS / COE issuances.',
    overview: 'Direct university tie-ups enabling application fee waivers, rapid offer letters, and prompt CAS / COE issuances. Our established institutional relationships accelerate your path from application to unconditional offer.',
    keyOfferings: [
      'Application fee waivers through direct university partner agreements.',
      'Priority processing lanes at 150+ partner universities globally.',
      'Rapid unconditional offer letter procurement within 3 to 7 business days.',
      'CAS (UK), COE (Australia), and LOA (Canada) verification and acceptance support.',
    ],
    processSteps: [
      'University Tie-Up Verification & Fee Waiver Enrollment',
      'Priority Application Submission',
      'Offer Letter Receipt & Conditions Clearance',
      'CAS/COE Issuance & Final Visa Preparation',
    ],
  },
  'finance-assistance': {
    title: 'Finance Assistance',
    subtitle: 'Structured education loans, fund verification, and financial documentation',
    metaTitle: 'Finance Assistance | Education Loans | 13 Dreams Consultants',
    metaDesc: 'Collateral and non-collateral education loan guidance through nationalized and private banking partners with 13 Dreams Consultants.',
    overview: 'Satisfying embassy financial proof rules is often the most critical hurdle in obtaining a study visa. Whether embassies demand 28-day funds (UK), GIC certificates (Canada), Blocked Accounts (Germany), or genuine bank loans (USA/Australia), our finance advisory wing guides parents and students on acceptable sponsorship structures that meet strict immigration compliance.',
    keyOfferings: [
      'Partnerships with nationalized banks (SBI, PNB, BOB) and premier private lenders (HDFC Credila, ICICI, Avanse).',
      'Assistance with collateral-free (unsecured) education loans up to ₹50-75 Lakhs.',
      'Guidance on acceptable co-signers, IT returns, and property evaluation reports.',
      'Speedy loan sanction letters directly acceptable by overseas universities and embassies.',
    ],
    processSteps: [
      'Initial Financial Assessment & Budget Calculation',
      'Bank Matching Based on Tuition Fees & Student Profile',
      'Document Submission & Income Verification',
      'Loan Sanction Letter Issuance & Direct University Disbursement',
    ],
  },
  'scholarship-guidance': {
    title: 'Scholarship Guidance',
    subtitle: 'Unlocking merit scholarships, early bird discounts, and government grants',
    metaTitle: 'Scholarship Guidance | 13 Dreams Consultants',
    metaDesc: 'Dedicated guidance for securing merit-based international scholarships, regional bursaries, and tuition fee reductions with 13 Dreams Consultants.',
    overview: 'Studying overseas is an invaluable investment, and securing financial awards makes it significantly more viable. Our scholarship guidance desk works closely with candidates from the very first counseling session to position their academic and extracurricular achievements effectively for competitive university scholarships and external grants.',
    keyOfferings: [
      'Comprehensive listing of early-bird discounts and regional diversity scholarships.',
      'Targeted statement of purpose coaching highlighting leadership, research, and community involvement.',
      'Review of external scholarship programs (Fulbright, Erasmus Mundus, DAAD, Australia Awards).',
      'Direct coordination with university admissions panels to advocate for candidate bursaries.',
    ],
    processSteps: [
      'Scholarship Eligibility Screening',
      'Application Window & Deadline Mapping',
      'Essay Formulation & Academic Recommendation Optimization',
      'Official Scholarship Application Lodgement & Award Confirmation',
    ],
  },
  'study-visa-consultants-bareilly': {
    title: 'Study Visa Consultants Bareilly',
    subtitle: 'Your premier overseas education and immigration consultancy in Bareilly & North India',
    metaTitle: 'Study Visa Consultants Bareilly | 13 Dreams Consultants',
    metaDesc: 'Best study visa consultants in Bareilly at Luthra Tower, Ekta Nagar. 15+ years of trusted visa guidance for Canada, UK, Australia, USA, and Germany.',
    overview: 'Located at Luthra Tower, 2nd Floor, C-56 Ekta Nagar, Opp. LIC Office, Model Town, Bareilly, 13 Dreams Consultants Private Limited is widely recognized as the top visa consultancy in the region. For over 15 years, our senior leadership and certified counseling staff have empowered thousands of students across Bareilly, Moradabad, Rampur, Shahjahanpur, Pilibhit, and Uttarakhand to achieve their global study ambitions.',
    keyOfferings: [
      'Prime Bareilly branch office easily accessible in Model Town, Ekta Nagar.',
      'Over 15 years of industry authority and thousands of verified student visa grants.',
      'Complete end-to-end guidance under one roof: IELTS/PTE training, course selection, admissions, visa filing, and education loans.',
      'Regular in-person visits by foreign university representatives for on-the-spot assessments.',
      'High client satisfaction rating and transparent, ethical fee structures.',
    ],
    processSteps: [
      'Walk-in or Book a Free Counseling Appointment at Our Bareilly Office',
      'Profile Assessment with Mr. Harpreet Singh and Senior Advisory Team',
      'Fast-Track University Application & Offer Letter Issuance',
      'Rigorous Visa Dossier Preparation & Mock Interviews',
      'Successful Visa Grant & Pre-Departure Farewell',
    ],
  },
};

export const countryPageData = {
  australia: {
    countryName: 'Australia',
    tagline: 'World-Class Education, High Living Standards, and Generous Post-Study Work Visas',
    bannerImg: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790672763/13dreams/destinations/study_in_australia.jpg',
    metaTitle: 'Study in Australia | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Complete guidance for Indian students to study in Australia. Learn about universities, courses, Subclass 500 visa, scholarships, and post-study work rights.',
    overview: 'Australia has a well-deserved reputation as one of the leading educational destinations. It is the world\'s third most popular destination for international students. Australian universities are globally recognized for excellence in research, innovation, and industry-oriented training. With vibrant multicultural cities like Melbourne, Sydney, Brisbane, and Perth, students enjoy exceptional quality of life and career exposure.',
    whyStudyPoints: [
      'Globally Ranked Institutions: 7 of the world\'s top 100 universities belong to Group of Eight (Go8).',
      'Post-Study Work Rights: Subclass 485 Temporary Graduate Visa provides 2 to 4 years of open work authorization.',
      'Part-Time Work Permission: Work up to 48 hours per fortnight during study terms and unlimited hours during vacations.',
      'Extensive Scholarships: Australian Awards and institutional merit fee reductions ranging from 15% to 50%.',
      'Simplified Student Visa (Subclass 500): Streamlined online lodgement with transparent financial requirements.',
    ],
    topUniversities: [
      'University of Melbourne', 'University of Sydney', 'UNSW Sydney', 'Monash University',
      'University of Queensland', 'Deakin University', 'RMIT University', 'La Trobe University',
    ],
    visaFacts: [
      'Subclass 500 Student Visa with genuine student assessment.',
      'Minimum IELTS score of 6.0 - 6.5 (or PTE equivalent of 50 - 58).',
      'Overseas Student Health Cover (OSHC) mandatory for entire duration.',
      '13 Dreams Bareilly & Khatima offices offer complete GTE documentation assistance.',
    ],
  },
  canada: {
    countryName: 'Canada',
    tagline: 'Diverse Society, World-Class Universities, and a Clear Pathway to Permanent Residency',
    bannerImg: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790672798/13dreams/destinations/study_in_canada.jpg',
    metaTitle: 'Study in Canada | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Study in Canada with 13 Dreams Consultants. Get expert guidance on universities, student visas, SDS applications, and PR pathways for Indian students.',
    overview: 'Canada has been rated the world\'s third-best country for education. The country\'s cost of living is lower than most English-speaking nations, and its warm multicultural society ensures outstanding social integration for Indian students. Canada\'s Express Entry and Provincial Nominee Programs (PNPs) create some of the most accessible permanent residency pathways available globally.',
    whyStudyPoints: [
      'Post-Graduation Work Permit (PGWP): Up to 3 years of open work permit tied to degree duration.',
      'Express Entry PR: Accumulate Canadian work experience toward permanent residency within 2 to 3 years.',
      'Student Direct Stream (SDS): Accelerated student visa for top academic performers.',
      'Low Cost vs. USA/UK: Tuition fees at top Canadian universities cost 20% to 30% less than comparable UK/US institutions.',
      'Bilingual Culture: Thriving French-speaking communities in Montreal and Quebec open doors to unique career advantages.',
    ],
    topUniversities: [
      'University of Toronto', 'University of British Columbia (UBC)', 'McGill University',
      'University of Alberta', 'University of Waterloo', 'Ryerson University',
      'George Brown College', 'Humber College',
    ],
    visaFacts: [
      'Canadian Study Permit from IRCC (Immigration, Refugees and Citizenship Canada).',
      'GIC (Guaranteed Investment Certificate) of CAD 10,000 required for SDS applicants.',
      'Minimum IELTS 6.0 overall for most universities.',
      'SDS stream guarantees processing within 20 business days for qualified applicants.',
    ],
  },
  uk: {
    countryName: 'UK',
    tagline: 'Prestigious 1-Year Master\'s Degrees, Graduate Route Visa, and World Heritage Academia',
    bannerImg: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790672799/13dreams/destinations/study_in_uk.jpg',
    metaTitle: 'Study in UK | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Study in the UK with expert guidance on Russell Group universities, Student Visa (Tier 4), Graduate Route, and IELTS requirements from 13 Dreams Consultants.',
    overview: 'The United Kingdom, or Great Britain, has been regarded as a hub of knowledge and quality education for centuries. With prestigious institutions such as Oxford, Cambridge, Imperial College, and the London School of Economics, a UK degree carries unmatched global prestige. One-year Master\'s programs save both time and money while the new Graduate Route Visa allows 2 years of post-study work.',
    whyStudyPoints: [
      'World-Renowned Institutions: Oxford, Cambridge, Imperial College — top 10 globally ranked universities.',
      '1-Year Master\'s Degrees: Save one full academic year of tuition and living costs vs. Australian/Canadian counterparts.',
      'Graduate Route Visa: 2 years of work authorization after Bachelor\'s, 3 years after Master\'s or PhD.',
      'Multicultural Cities: London, Manchester, Birmingham host vibrant Indian student communities.',
      'Pathway to Settlement: 5-year residency route available for eligible graduates securing skilled employment.',
    ],
    topUniversities: [
      'University of Oxford', 'University of Cambridge', 'Imperial College London',
      'University College London (UCL)', 'University of Edinburgh', 'University of Manchester',
      'University of Birmingham', 'Coventry University',
    ],
    visaFacts: [
      'UK Student Visa (previously Tier 4) with CAS from a licensed sponsor university.',
      '28-day bank balance requirement (tuition fees + £1,334/month for London living).',
      'Minimum IELTS 6.0-6.5 (UKVI-approved test center only).',
      '13 Dreams provides complete CAS verification and financial documentation support.',
    ],
  },
  usa: {
    countryName: 'USA',
    tagline: 'Home to the World\'s Top Research Universities and the Largest International Student Ecosystem',
    bannerImg: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790672800/13dreams/destinations/study_in_usa.jpg',
    metaTitle: 'Study in USA | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Study in the USA with 13 Dreams Consultants. Complete F-1 visa guidance, I-20 processing, OPT/STEM OPT extension advice, and top university applications.',
    overview: 'The majority of students across the world dream about studying in the United States, which tops the list of the 10 most popular countries for global academia. Home to Harvard, MIT, Stanford, Caltech, and over 4,000 accredited institutions, the USA offers unprecedented academic breadth across STEM, business, arts, and humanities with the globally coveted F-1 Student Visa pathway.',
    whyStudyPoints: [
      'World\'s No. 1 Education Destination: 8 of the global Top 10 universities reside in the USA.',
      'OPT (Optional Practical Training): 1 year of post-study work with 3-year STEM OPT extension.',
      'Research & Funding Opportunities: Extensive TA and RA stipend positions for postgraduate students.',
      'Campus Diversity: A rich multicultural environment with India being the largest source country of international students.',
      'Career Networking: Access to Silicon Valley, Wall Street, and Fortune 500 corporate recruiting networks.',
    ],
    topUniversities: [
      'Massachusetts Institute of Technology (MIT)', 'Stanford University', 'Harvard University',
      'California Institute of Technology (Caltech)', 'University of Chicago',
      'University of California, Berkeley', 'Carnegie Mellon University', 'Purdue University',
    ],
    visaFacts: [
      'F-1 Student Visa with I-20 from a SEVP-certified institution.',
      'SEVIS (Student Exchange Visitor Information System) fee payment required.',
      'Embassy interview mandatory — 13 Dreams provides mock interview prep.',
      'Maintain full-time enrollment status as per F-1 regulations.',
    ],
  },
  'new-zealand': {
    countryName: 'New Zealand',
    tagline: 'Peaceful Living, High Quality Education, and Strong Post-Study Work Rights',
    bannerImg: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790672801/13dreams/destinations/study_in_new_zealand.jpg',
    metaTitle: 'Study in New Zealand | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Study in New Zealand with 13 Dreams Consultants. Expert guidance on student visas, top universities, partner and post-study work rights.',
    overview: 'New Zealand is a gorgeous, safe, and welcoming country consistently ranked among the world\'s most peaceful nations. Its universities are internationally accredited and offer modern, research-oriented programs. New Zealand\'s post-study work rights and partner open work permits add significant financial value to an already affordable study destination.',
    whyStudyPoints: [
      'Post Study Work Visa: Up to 3 years of open work authorization depending on study level and institution.',
      'Paid Work Rights: Work 20 hours per week during term and full-time during breaks.',
      'Partner Work Rights: Full-time open work permit for spouses of students pursuing Master\'s degrees in Green List areas.',
      'Peaceful & Safe: Ranked consistently among the top 3 most peaceful nations in the Global Peace Index.',
    ],
    topUniversities: [
      'University of Auckland', 'University of Otago', 'Victoria University of Wellington',
      'University of Canterbury', 'Massey University', 'University of Waikato',
      'Lincoln University', 'Auckland University of Technology (AUT)',
    ],
    visaFacts: [
      'Fee Paying Student Visa with transparent fund verification.',
      'Payment of tuition fees only required AFTER Approval in Principle (AIP).',
      'Special assistance with Immigration New Zealand (INZ) documentation at 13 Dreams.',
    ],
  },
  germany: {
    countryName: 'Germany',
    tagline: 'Tuition-Free Education, Europe\'s Largest Economy, and 18 Months Post-Study Work Visas',
    bannerImg: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790672801/13dreams/destinations/study_in_germany.jpg',
    metaTitle: 'Study in Germany | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Explore tuition-free universities, English-taught Master\'s degrees, APS certificate processing, and 18-month job seeker visas in Germany with 13 Dreams Consultants.',
    overview: 'There is so much more Germany has to offer to international students. Tuition fees are negligible in public universities, while academic standards in mechanical engineering, computer science, automotive design, and renewable energy are world-leading. Graduating from a German university opens direct doors to high-paying careers across the European Union with streamlined EU Blue Card permanent residency pathways.',
    whyStudyPoints: [
      'Zero Tuition Fees: Most public universities charge only a nominal administration fee (€150 to €350 per semester).',
      '18-Month Job Seeker Visa: Upon graduation, students receive 1.5 years to secure employment matching their degree.',
      'English-Taught Degrees: Over 1,500 Master\'s programs conducted completely in English.',
      'Strongest European Economy: Europe\'s industrial hub with acute demand for IT engineers, data scientists, and technicians.',
      'Part-Time Work: Allowed to work 140 full days or 280 half days per calendar year.',
    ],
    topUniversities: [
      'Technical University of Munich (TUM)', 'RWTH Aachen University', 'TU Berlin',
      'University of Stuttgart', 'Karlsruhe Institute of Technology (KIT)', 'Heidelberg University',
      'IU International University of Applied Sciences', 'SRH Berlin University of Applied Sciences',
    ],
    visaFacts: [
      'National Student Visa (Type D) with Blocked Account (Sperrkonto).',
      'Mandatory APS (Akademische Prüfstelle) certificate required for Indian applicants.',
      'Health insurance verification via TK, Barmer, or Coracle.',
      'End-to-end blocked account and APS submission assistance provided by 13 Dreams team.',
    ],
  },
  malta: {
    countryName: 'Malta',
    tagline: 'Schengen Visa Privileges, 100% English-Taught Degrees, and Affordable European Education',
    bannerImg: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790672802/13dreams/destinations/study_in_malta.jpg',
    metaTitle: 'Study in Malta | Schengen Visa & English-Taught Degrees | 13 Dreams',
    metaDesc: 'Study in Malta with European Schengen access, affordable tuition from €5,000/yr, 20 hrs/week part-time work, and English-speaking education with 13 Dreams Consultants.',
    overview: 'Malta is an enchanting Mediterranean island nation, a prominent member of both the European Union and the Schengen Zone, and one of only two official English-speaking countries in the EU. Renowned for its safe coastal environment, 300 days of annual sunshine, and British-patterned higher education, Malta delivers internationally accredited degrees at tuition fees substantially lower than the UK or Western Europe. Students gain seamless visa-free travel across 27 Schengen countries, part-time work authorization, and accessible pathways into the European workforce.',
    whyStudyPoints: [
      'Official English-Speaking EU Nation: Over 90% of the population speaks fluent English, ensuring effortless daily communication, academic instruction, and professional integration.',
      'Schengen Area Privileges: Travel freely across 27 European nations (including Germany, France, Italy, Switzerland) without additional visas during study breaks.',
      'Highly Affordable European Tuition: Internationally accredited Bachelor\'s and Master\'s programs starting from just €5,000 to €8,500 per academic year.',
      'Part-Time Work Regulations: Students must first receive their Temporary Residence Card (TRC) and have their employer apply for a working license through Jobsplus before working 20 hours/week.',
      'Identità Tuition Deposit Requirement: Students are typically required by Identità to show proof of a 50% upfront tuition deposit for courses over €2,500 before applying for the visa.',
      'Post-Study Work Permit: Graduates are eligible for a 6-month post-study residence permit specifically to search for employment in Malta.',
      'High Visa Success & Simplified Finances: Transparent bank balance requirements with no complicated blocked accounts, and fast processing through the Central Visa Unit (CVU).',
    ],
    topUniversities: [
      'University of Malta (Public Research University)',
      'MCAST (Malta College of Arts, Science and Technology)',
      'Global College Malta (SmartCity)',
      'Queen Mary University of London (Malta Campus - Medicine)',
      'London School of Commerce (LSC) Malta',
      'American University of Malta',
      'Domain Academy Malta',
      'Ascencia Business School Malta',
    ],
    visaFacts: [
      'National Long Stay (Type D) Schengen Student Visa issued via Central Visa Unit (CVU) & VFS Global.',
      'Tuition Deposit: Students are typically required by Identità to show proof of a 50% upfront tuition deposit for courses over €2,500 before applying for the visa.',
      'Part-Time Work (Jobsplus): Students must first receive their Temporary Residence Card (TRC) and have their employer apply for a working license through Jobsplus before working 20 hours/week.',
      'Post-Study Work Rights: Graduates are eligible for a 6-month post-study residence permit specifically to search for employment in Malta.',
      'Proof of living funds: Bank balance covering approx. €25 to €30 per day of stay (no blocked account required).',
      'English proficiency: IELTS 5.5–6.0 overall, with Medium of Instruction (MOI) English waivers available for qualified applicants.',
      'Comprehensive Schengen medical travel insurance with minimum €30,000 emergency coverage.',
      '13 Dreams Bareilly & Khatima teams provide complete document vetting, financial affidavit assistance, and fast-track submission.',
    ],
    keywords: [
      'Study in Malta',
      'Study in Malta for Indian students',
      'Malta student visa requirements',
      'Malta Schengen student visa',
      'Affordable European universities in Malta',
      'Malta study abroad consultants',
      'Jobsplus student work rights Malta',
      'University of Malta admission',
    ],
  },
  singapore: {
    countryName: 'Singapore',
    tagline: 'Asia\'s Premier Financial & Tech Capital, High Global Safety, and World-Class Universities',
    bannerImg: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790672803/13dreams/destinations/study_in_singapore.jpg',
    metaTitle: 'Study in Singapore | Asian Global Education Hub | 13 Dreams',
    metaDesc: 'Study in Singapore. World-class Asian business hub, international university branch campuses, fast-track degrees, and Solar+ visas with 13 Dreams Consultants.',
    overview: 'Singapore is the educational, economic, and technological powerhouse of Asia, consistently ranked among the world\'s safest, cleanest, and most competitive economies. Home to top-ranked Asian universities and prestigious branch campuses of leading Australian and British universities, Singapore offers students the opportunity to earn internationally recognized degrees in accelerated 2-year Bachelor\'s or 1-year Master\'s timelines. With headquarters of over 7,000 global multinationals, students gain unparalleled corporate networking, high-paying internships, and fast digital visa processing.',
    whyStudyPoints: [
      'Global Corporate & Financial Capital: Asia-Pacific headquarters of Google, Microsoft, Meta, Apple, Dyson, and DBS, creating unparalleled internship and graduate employment opportunities.',
      'World-Ranked Branch Campuses: Earn authentic Australian or UK university degrees (James Cook University, Curtin, Coventry, Murdoch) at 30% to 40% lower costs than living in the West.',
      'Accelerated Degree Formats: Fast-track trimesters enable students to complete Bachelor\'s degrees in just 2 years and Master\'s in 1 year, significantly saving tuition and living expenses.',
      'Part-Time Work Regulations: Part-time work (up to 16 hours/week) is strictly permitted only for students enrolled at approved IHLs. Students at private institutes (PEIs) are not permitted to work during their studies.',
      'Post-Graduation Stay Pathways (LTVP vs EP/S-Pass): LTVP for job-seeking is generally available for graduates of Institutes of Higher Learning (IHLs/Public Universities). Graduates from Private Education Institutions (PEIs) must typically secure an S-Pass or Employment Pass (EP) to remain and work.',
      'Unsurpassed Safety & Infrastructure: Consistently rated the safest city in the world with state-of-the-art public transit, green architecture, and an English-speaking business environment.',
      'Streamlined Solar+ Visa: 100% digital Student\'s Pass (STP) application through Singapore ICA with NO embassy interview required and rapid 2 to 4 weeks turnaround.',
      'English Waiver & Placement Testing: Multiple premier institutions offer internal English proficiency placement tests or pathway courses, removing mandatory external IELTS/PTE hurdles.',
    ],
    topUniversities: [
      'National University of Singapore (NUS - Global Top 10)',
      'Nanyang Technological University (NTU - Global Top 15)',
      'Singapore Management University (SMU)',
      'James Cook University (JCU) Singapore (Australian Public University)',
      'Curtin Singapore (Branch Campus of Curtin University, Australia)',
      'PSB Academy (Coventry & Newcastle partnerships)',
      'Kaplan Higher Education Academy Singapore (UCD & Murdoch degrees)',
      'MDIS (Management Development Institute of Singapore)',
      'Amity Global Institute Singapore',
    ],
    visaFacts: [
      'Student\'s Pass (STP) application filed online through the Immigration & Checkpoints Authority (ICA) SOLAR+ system.',
      'In-Principle Approval (IPA) issued within 2 to 4 weeks, serving as the pre-approved entry visa with zero embassy interview.',
      'Part-Time Work Regulations: Part-time work (up to 16 hours/week) is strictly permitted only for students enrolled at approved IHLs. Students at private institutes (PEIs) are not permitted to work during their studies.',
      'Long Term Visit Pass (LTVP) & Employment: LTVP for job-seeking is generally available for graduates of Institutes of Higher Learning (IHLs/Public Universities). Graduates from Private Education Institutions (PEIs) must typically secure an S-Pass or Employment Pass (EP) to remain and work.',
      'Transparent bank balance requirement for living expenses with no long seasoning or blocked accounts.',
      '13 Dreams Consultants handles 100% of SOLAR+ filing, document compliance, and post-arrival accommodation guidance.',
    ],
    keywords: [
      'Study in Singapore',
      'Study in Singapore for Indian students',
      'Singapore student visa ICA Solar',
      'Study in Singapore without IELTS',
      'James Cook Singapore admissions',
      'Curtin Singapore degrees',
      'Singapore study abroad consultants',
      'Singapore fast track degrees',
    ],
  },
  netherlands: {
    countryName: 'Netherlands',
    tagline: 'Over 2,100 English-Taught Programs, Top 100 Global Universities, and 1-Year Zoekjaar Post-Study Work Visa',
    bannerImg: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790672804/13dreams/destinations/study_in_netherlands.jpg',
    metaTitle: 'Study in Netherlands (Holland) | Top Universities & Zoekjaar Visa | 13 Dreams',
    metaDesc: 'Complete guide for Indian students to study in the Netherlands. Explore English-taught degrees, TU Delft, University of Amsterdam, Orientation Year (Zoekjaar) visa, and scholarships with 13 Dreams Consultants.',
    overview: 'The Netherlands (Holland) is Continental Europe’s undisputed leader in English-taught higher education, offering more than 2,100 internationally accredited Bachelor’s and Master’s degree programs taught 100% in English. Renowned for its innovative problem-based learning (PBL) methodology, world-class research infrastructure, and multicultural open society, the Netherlands is home to 12 universities ranked among the world’s top 200. International graduates enjoy the prestigious "Zoekjaar" (Orientation Year) residence permit, granting one full year of unrestricted employment rights in Europe’s most technologically advanced economy.',
    whyStudyPoints: [
      'Pioneers in English Higher Education: First non-English speaking nation to design university courses specifically in English, with over 95% of the population speaking fluent English.',
      'World-Class Academic Ranking: Institutions like TU Delft, University of Amsterdam, and Erasmus University Rotterdam consistently rank in the global Top 50–100.',
      'Orientation Year Visa (Zoekjaar): 1-year post-study work permit enabling graduates to work without work permits or sponsor quotas, leading directly into the Highly Skilled Migrant (Kennismigrant) scheme.',
      'Part-Time Work & TWV Permit: Up to 16 hours per week during term-time or full-time during summer months. Note: The Dutch employer must apply for the student\'s work permit (TWV) on their behalf.',
      'Early Application Deadlines: Early application deadlines apply: Because the Dutch university applies for the visa on your behalf, applications for the September intake typically close in April or May.',
      'Schengen Advantage & European Connectivity: Central location in Western Europe with high-speed rail connectivity to Paris, Brussels, London, and Berlin.',
      'Generous Scholarships: Access to NL Scholarship (formerly Holland Scholarship), Orange Tulip Scholarship (OTS), and university-specific merit awards ranging from €5,000 to full tuition coverage.',
      'Thriving Innovation Hub: Headquarters to global titans like ASML, Philips, Shell, Unilever, Booking.com, and Heineken with urgent demand for international STEM and business talent.',
    ],
    topUniversities: [
      'University of Amsterdam (UvA)',
      'Delft University of Technology (TU Delft)',
      'Erasmus University Rotterdam',
      'Utrecht University',
      'Leiden University',
      'Eindhoven University of Technology (TU/e)',
      'University of Groningen',
      'Vrije Universiteit Amsterdam (VU)',
      'Radboud University',
      'Wageningen University & Research',
      'Fontys University of Applied Sciences',
      'Saxion University of Applied Sciences',
    ],
    visaFacts: [
      'MVV (Provisional Residence Permit) & VVR (Residence Permit) applied directly on your behalf by your Dutch sponsor university through IND (Immigration and Naturalisation Service).',
      'Early application deadlines apply: Because the Dutch university applies for the visa on your behalf, applications for the September intake typically close in April or May.',
      'Part-time work permitted: Up to 16 hours per week during term-time or full-time during summer months. Note: The Dutch employer must apply for the student\'s work permit (TWV) on their behalf.',
      'Orientation Year (Zoekjaar): 1-year post-study open work permit enabling graduates to work without sponsor quotas or work permits.',
      'Proof of living funds mandated by IND (approx. €1,000–€1,250/month, ~€12,500/year) via bank deposit or sponsor guarantee.',
      'English proficiency: IELTS 6.0 (UG) or 6.5 (PG), with PTE Academic (58–65) and TOEFL iBT accepted by universities.',
      '13 Dreams Consultants provides complete document vetting, university liaison, scholarship matching, and IND visa assistance.',
    ],
    keywords: [
      'Study in Netherlands',
      'Study in Holland for Indian students',
      'Netherlands student visa IND MVV',
      'Zoekjaar visa orientation year',
      'English taught degrees Netherlands',
      'TU Delft admissions',
      'University of Amsterdam for international students',
      'Netherlands scholarships Indian students',
    ],
  },
  ireland: {
    countryName: 'Ireland',
    tagline: 'European Silicon Valley, 2-Year Post-Study Work Visas, and World-Renowned Research Universities',
    bannerImg: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790672805/13dreams/destinations/study_in_ireland.jpg',
    metaTitle: 'Study in Ireland | Top Consultants & Visa Guidance | 13 Dreams',
    metaDesc: 'Study in Ireland with 13 Dreams Consultants. Learn about Trinity College, UCD, Third Level Graduate Scheme (2-year work permit), and European tech hub careers.',
    overview: 'Ireland is Europe’s primary technology and pharmaceutical hub, hosting European headquarters of Google, Apple, Meta, Microsoft, and Pfizer. As an English-speaking country in the European Union, Ireland combines historic academic institutions with forward-looking industry internships, making it one of the most popular and financially rewarding study destinations for Indian students.',
    whyStudyPoints: [
      'European Tech Capital: Dublin is home to European headquarters for top global tech, finance, and biotech corporations.',
      'Third Level Graduate Scheme: Up to 2 years of open post-study work authorization for Master’s graduates.',
      'English-Speaking EU Member: Smooth cultural integration and unrestricted European career connections.',
      'Affordable Tuition Fees: Highly competitive tuition costs compared to the US and UK.',
      'Part-Time Work Permission: Work up to 20 hours per week during term and 40 hours during holidays.',
    ],
    topUniversities: [
      'Trinity College Dublin (TCD)', 'University College Dublin (UCD)', 'University of Galway',
      'University College Cork (UCC)', 'Dublin City University (DCU)', 'University of Limerick',
      'Maynooth University', 'Technological University Dublin (TU Dublin)',
    ],
    visaFacts: [
      'Irish Student Visa (Stamp 2) with valid acceptance and proof of funds.',
      'Minimum IELTS requirement typically 6.0 - 6.5 overall.',
      'Private medical insurance is mandatory for international students.',
      'End-to-end documentation scrutiny and visa lodgement with 13 Dreams Bareilly.',
    ],
  },
  switzerland: {
    countryName: 'Switzerland',
    tagline: 'World Capital of Hospitality, Elite Scientific Research, and Exceptional Quality of Life',
    bannerImg: 'https://res.cloudinary.com/eikgki2a/image/upload/v1790672806/13dreams/destinations/study_in_switzerland.jpg',
    metaTitle: 'Study in Switzerland | Hospitality & Top Universities | 13 Dreams',
    metaDesc: 'Explore studying in Switzerland with 13 Dreams Consultants. Global leader in hospitality management, ETH Zurich, cutting-edge science, and high living standards.',
    overview: 'Switzerland is world-renowned for its pristine natural beauty, exceptional safety, and unparalleled global reputation in hospitality management, banking, luxury brand administration, and scientific research. Home to ETH Zurich and the world’s most prestigious hotel schools, Switzerland offers international students an elite learning environment and global executive career pathways.',
    whyStudyPoints: [
      'Global Leader in Hospitality: Home to top-ranked hotel and luxury management schools worldwide.',
      'World-Class Research: Institutions like ETH Zurich consistently rank among the top 10 universities globally.',
      'Paid Industry Internships: Hospitality programs typically include structured, high-paying Swiss internships.',
      'Heart of Europe: Central Schengen location allows seamless travel across all European capitals.',
      'Pristine Living & Safety: Consistently ranked at the pinnacle of global happiness and safety indices.',
    ],
    topUniversities: [
      'ETH Zurich', 'EPFL (Lausanne)', 'University of Zurich', 'University of Geneva',
      'EHL Hospitality Business School', 'Glion Institute of Higher Education',
      'Les Roches Global Hospitality Education', 'Swiss Hotel Management School (SHMS)',
    ],
    visaFacts: [
      'Swiss National Visa (Type D) for long-term academic studies.',
      'Evidence of financial capability and accommodation confirmation required.',
      'Clear motivation statement and educational credential apostille.',
      'Complete embassy file review and preparation by 13 Dreams senior team.',
    ],
  },
};

